# catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bs-exp-a-1
  description: API som räddar världen
  annotations:
    backstage.io/techdocs-ref: dir:./docs
spec:
  type: service
  lifecycle: production
  owner: team-ironman
